// netlify/lib/rssSourcesByLang.js
//
// RSS источники новостей по языкам
// Микс: агентства + аналитика + мир + права + технологии

const RSS_SOURCES = {
  ru: [
    { name: "BBC Russian", url: "https://www.bbc.com/russian/index.xml" },
    { name: "DW Russian", url: "https://www.dw.com/ru/rss/rss-ru-all" },
    { name: "Meduza", url: "https://meduza.io/rss/all" },
    { name: "Медуза", url: "https://meduza.io/rss/all" },
    { name: "Новая газета", url: "https://novayagazeta.ru/rss" },
    { name: "Радио Свобода", url: "https://www.svoboda.org/api/zrqitewimt" },
    { name: "The Insider", url: "https://theins.ru/rss/all.xml" },
    { name: "Republic", url: "https://republic.ru/rss/all.xml" },
    { name: "Lenta.ru", url: "https://lenta.ru/rss" },
    { name: "Коммерсант", url: "https://www.kommersant.ru/RSS/news.xml" },
    { name: "Ведомости", url: "https://www.vedomosti.ru/rss/news" },
    { name: "РБК", url: "https://www.rbc.ru/rbcfreenews.rss" },
    { name: "Газета.ру", url: "https://www.gazeta.ru/export/rss/lenta.xml" },
    { name: "Интерфакс", url: "https://www.interfax.ru/rss.asp" },
    { name: "РИА Новости", url: "https://ria.ru/export/rss2/index.xml" },
    { name: "ТАСС", url: "https://tass.ru/rss/v2.xml" },
    { name: "RT", url: "https://russian.rt.com/rss" },
    { name: "Sputnik", url: "https://sputniknews.com/rss/" },
    { name: "Эхо Москвы", url: "https://echo.msk.ru/rss/all.xml" },
    { name: "Московский комсомолец", url: "https://www.mk.ru/rss/index.xml" },
    { name: "Независимая газета", url: "https://www.ng.ru/rss/" },
    { name: "Российская газета", url: "https://rg.ru/xml/index.xml" },
    { name: "Взгляд", url: "https://vz.ru/rss.xml" },
    { name: "Forbes Russia", url: "https://www.forbes.ru/rss.xml" },
    { name: "Ведомости", url: "https://www.vedomosti.ru/rss/news" },
  ],
  
  en: [
    { name: "BBC World", url: "https://feeds.bbci.co.uk/news/world/rss.xml" },
    { name: "BBC News", url: "https://feeds.bbci.co.uk/news/rss.xml" },
    { name: "The Guardian World", url: "https://www.theguardian.com/world/rss" },
    { name: "The Guardian", url: "https://www.theguardian.com/uk/rss" },
    { name: "DW World", url: "https://rss.dw.com/rdf/rss-en-all" },
    { name: "Reuters World", url: "https://www.reuters.com/rssFeed/worldNews" },
    { name: "Reuters Top News", url: "https://www.reuters.com/rssFeed/topNews" },
    { name: "AP News", url: "https://apnews.com/apf-topnews" },
    { name: "AP World", url: "https://apnews.com/apf-worldnews" },
    { name: "CNN World", url: "http://rss.cnn.com/rss/edition.rss" },
    { name: "CNN Top Stories", url: "http://rss.cnn.com/rss/cnn_topstories.rss" },
    { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml" },
    { name: "NPR World", url: "https://feeds.npr.org/1004/rss.xml" },
    { name: "NPR News", url: "https://feeds.npr.org/1001/rss.xml" },
    { name: "The New York Times World", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml" },
    { name: "The New York Times", url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml" },
    { name: "The Washington Post World", url: "https://feeds.washingtonpost.com/rss/world" },
    { name: "The Washington Post", url: "https://feeds.washingtonpost.com/rss/world" },
    { name: "Financial Times", url: "https://www.ft.com/?format=rss" },
    { name: "The Economist", url: "https://www.economist.com/rss.xml" },
    { name: "Foreign Policy", url: "https://foreignpolicy.com/feed/" },
    { name: "Foreign Affairs", url: "https://www.foreignaffairs.com/feed" },
    { name: "Politico", url: "https://www.politico.com/rss/politicopicks.xml" },
    { name: "The Hill", url: "https://thehill.com/rss/syndicator/19110" },
    { name: "Axios", url: "https://www.axios.com/feed/all.xml" },
    { name: "Vox", url: "https://www.vox.com/rss/index.xml" },
    { name: "The Atlantic", url: "https://www.theatlantic.com/feed/all/" },
    { name: "Wired", url: "https://www.wired.com/feed/rss" },
    { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
    { name: "The Verge", url: "https://www.theverge.com/rss/index.xml" },
    { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index" },
    { name: "MIT Technology Review", url: "https://www.technologyreview.com/feed/" },
    { name: "Nature News", url: "https://www.nature.com/nature.rss" },
    { name: "Science Daily", url: "https://www.sciencedaily.com/rss/all.xml" },
    { name: "Human Rights Watch", url: "https://www.hrw.org/rss" },
    { name: "Amnesty International", url: "https://www.amnesty.org/en/rss/" },
    { name: "Freedom House", url: "https://freedomhouse.org/rss" },
    { name: "Reporters Without Borders", url: "https://rsf.org/en/rss" },
    { name: "UN News", url: "https://news.un.org/feed/" },
    { name: "EU Observer", url: "https://euobserver.com/rss" },
    { name: "Euronews", url: "https://www.euronews.com/rss?format=mrss" },
  ],
  
  de: [
    { name: "Tagesschau", url: "https://www.tagesschau.de/xml/rss2" },
    { name: "DW German", url: "https://rss.dw.com/rdf/rss-de-all" },
    { name: "Der Spiegel", url: "https://www.spiegel.de/schlagzeilen/index.rss" },
    { name: "Die Zeit", url: "https://newsfeed.zeit.de/index" },
    { name: "Süddeutsche Zeitung", url: "https://www.sueddeutsche.de/rss" },
    { name: "Frankfurter Allgemeine", url: "https://www.faz.net/rss/aktuell/" },
    { name: "Die Welt", url: "https://www.welt.de/feeds/section/home.rss" },
    { name: "taz", url: "https://taz.de/!p4606;rss/" },
    { name: "Neue Zürcher Zeitung", url: "https://www.nzz.ch/international.rss" },
    { name: "Der Standard", url: "https://www.derstandard.at/rss" },
    { name: "ORF", url: "https://orf.at/stories/s/index.rss" },
    { name: "ARD", url: "https://www.ard.de/home/ard/ARD_Startseite_Neu_100~rss.xml" },
    { name: "ZDF", url: "https://www.zdf.de/rss/zdf/nachrichten" },
    { name: "Bild", url: "https://www.bild.de/rssfeeds/rss3-16725492,feed=home.bild.html" },
    { name: "Focus", url: "https://www.focus.de/feed/rss" },
    { name: "Stern", url: "https://www.stern.de/feed/standard/alle-nachrichten/" },
    { name: "Handelsblatt", url: "https://www.handelsblatt.com/contentexport/feed/schlagzeilen" },
    { name: "WirtschaftsWoche", url: "https://www.wiwo.de/contentexport/feed/rss" },
    { name: "Deutsche Welle", url: "https://rss.dw.com/rdf/rss-de-all" },
    { name: "Heise", url: "https://www.heise.de/rss/heise.rdf" },
    { name: "Golem", url: "https://www.golem.de/rss" },
    { name: "Netzpolitik", url: "https://netzpolitik.org/feed/" },
    { name: "Telepolis", url: "https://www.heise.de/tp/rss/artikel/2/2/1/1/1/1/1" },
    { name: "Cicero", url: "https://www.cicero.de/rss" },
  ],
};

module.exports = {
  RSS_SOURCES,
};
